### ISSUE TITLE
Query alias inconsistency

### ISSUE THREAD

**Issue by Tejas-ChandraShekarRaju** [aravindathreya/bAhMaterialMgmt#5]
1. projects_with_no_operations_team():
2. projects_with_operations_team():

Using p  instead of P -> case mismatch

**Comment by Tejas-ChandraShekarRaju** [comment]
Also reconfirm if column name is approved or is_approved -> been used differently in different functions. 
Ex- check unapproved_projects which is using is_approved vs projects_with_no_operations_team(): which is using approved

**Comment by aravindathreya** [comment]
This is fixed
